### ISSUE TITLE
How can i run this?

### ISSUE THREAD

**Issue by cymruu** [kmyk/mersenne-twister-predictor#1]
Hi, i created file with example data 
[data.txt](https://github.com/kmyk/mersenne-twister-predictor/files/320222/dane.txt)
(results of php function mt_rand one in each line)
How it's supposed to be formated? 
and i run the script with `python3.5 predict.py data.txt` and the output is strange 
`�≠�G U�P�J�⎽≤�D≥3�UbF�3�(Q������$�$��Ѷ
└�°���85☃�����K�"��L��◆↓┴↑��S�Y(DZ��A<�M°#����↓=#�꯰7�↑ц⎼8'Z
                                                           ��$�≠┐��└!'�┬�W������[!└�→   �U��4@P�%��H┼I�H��≥±����1?�S�˲���]�X���/┘d���QK�⎻��ХJ?≤d
�)8�┴%
���"�,�3U�x�N�̿��\�ﾂ*X���h�Ev&�L��ۓ)6��Q�E�y"�=43��eۆz��1�>
��@^�l�
 �D�2[X|�a�)E�!,
�W�JfR7t&ӱC@(+s��?�i�:�Ӂ%xm�juaw���%�؟��FJ�.޴MS犇��Ւ↓H�8���≥3�OV⎻P!��⎺
                                                                      ┐◆��@*9�K
                                                                               ���ˇ◆�ٮ;�π└ù��?<�D┘      '�┼���W1⎻?≥&�⎺��K��U��↑☃▒�𰣈�e�!ſb��7�┤D�·���G┘  Kd���[�│£�$�↓R�└DA�≥&:W┴⎼*┐K│���QFb6┤)C�◆≤���T≥���▮�π┴L�ֳ!▮→XZ┼≠�≥�_���?[b/�<┘Ծ'����☃W≠─↓Պ;�┴�A
 ┐լ���O��Yh�nSyp:��mP�B�eɗ?���B Ԙ{�1)3vX̓�obmMÕة{,�17|�
                                                      $O�؂�F���;%S^E�71�y��>�i
�p�RE���p*ec�Oc[�Rxg��:[޹9��1�.xAR�C�*w[��Ʈ�/2<��/P4���"i���X����"I��┴�E��M���└[─�����^�V┼◆��]�3�]�⎻�D↑b£�ۖ������£�Z┌����Ɣ٬°�°���←┴J�QT�>�±�ܩƶ�I�0oo�m���Eax&Z�Fڥ�팋{
                                                                 l��c�6�a�_^!p�*9ix�p£�1x
r����%F|X�C]v���R�I>7~Z�^Z]��                                                            ��Fxi}D}߷�+<8
                             6��,����7t�J������I��Hw(q�
                                                       ��O��┴��<↓┘eL˘↑@�
մ�هOʓ�S(≠π£�·   С�Eπ��O⎺��WI_�                                          S⎼�⎽├2:��⎺◆���
�bπ2�⎻≤�ْ�B�⎺├←2↓E�9R��┴Y�▮≠�┬���]���8�G�W��┼�?���C↑H�
4�M�T��8� π≠]�                                       ←���2��┐L↓M⎻ʅ%≥≥B��>��N��_;���├(≤?└�U⎽d�ϲ⎻�┤£��O�┤
��≥�G!K5├�      ◆�� ��

                      �e�▮�←    π→Fc�݄M�Q=CT@�������@�→��±�↑�┤│J���2�≠Z�'�→R=�Eb6�L?4┐[
�QD�·�8ߑ�eW]I&�ց9C"⎻>c���2/W���>�^��⎺�%_=_ԸÅ:##�≥'';� �⎼)��                           4⎽e┼M�c��↑I����°���'7�����!��↓� ⎽�5˄ו_�D4���6(─┌��_���D│£��(└┴@�⎺����2�C4│������:�_e���☃‸�K5▮·4���)2S�↑6b£≥8�à�>┤��d
≠��*��5K│⎼�┴�%���▒?�⎼┤e_�Iޏ*�ݲ
                              ├�Ȳ�
                                 ┘�1☃│  �Z�7P)≥>B�)�←���)↑└�4���λ┤F���┤�\�!H�* ▮Y�`

Thanks in advance

**Comment by kmyk** [comment]
I made the interface more natural one, and write some example. Please see the (updated) readme.

The original interface was binary packed one, numbers represented as 624 * 32 byte with little endian.
This was for the original problem which I wanted to solve. But it seems the interface is not natural and confusing, so I changed it now. (And those who want to use the original interface should write some code, like perl oneliner.)

By the way, I heard that the php's `mt_rand` has a bug in some version. If you use a `mt_rand` of such version, this predictor doesn't work. (<https://github.com/php/php-src/commit/a0724d30817600540946b41e40f4cfc2a0c30f80>)

**Comment by cymruu** [comment]
@kmyk thank you very much! i'm taking a look right
