### ISSUE TITLE
can it predict 30 random numbers?

### ISSUE THREAD

**Issue by fisch123456** [kmyk/mersenne-twister-predictor#10]
Hi, this is probably a stupid question but I want to predict 30 random numbers.Is it possible to do it?It is version from Makoto Saito.
Thanks for reply

**Comment by fisch123456** [comment]
こんにちは、これはばかげた質問かもしれませんが、30個の乱数を予測したいのですが、それは可能ですか？サイトウマコトのバージョンです。
返信ありがとうございます

**Comment by fisch123456** [comment]
こんにちは、これはばかげた質問かもしれませんが、30個の乱数を予測したいのですが、それは可能ですか？サイトウマコトのバージョンです。
お返事ありがとうございます

**Comment by fisch123456** [comment]
こんにちは、これはおそらくばかげた質問ですが、30個の乱数を予測したいと思います。

**Comment by kmyk** [comment]
You are talking about the prediction about values of SIMD-oriented Fast Mersenne Twister (SFMT) in "SIMD-oriented Fast Mersenne Twister: a 128-bit Pseudorandom Number Generator", Mutsuo Saito and Makoto Matsumoto, right?
Also, you would like to predict the future 30 outputs, in the situation when you already have the history of enough number of past outputs, right?

In terms of SFMT, this library doesn't support it. You need to find the algorithm to predict SFMT (if it exists), and need to implement it. SFMT seems a variant of the standard MT, so we might be able to use a similar way to the prediction, but I don't know whether this is possible.

For the "30" (why "30"?), it's not a problem. If you could predict one number, then you can repeat it 30 times.

**Comment by fisch123456** [comment]
Hi, I want to predict numbers for the game but I don't know which variant it uses if it not support SFMT can it support other versions?Thanks.

**Comment by kmyk** [comment]
1. It's impossible to predict if you don't know what variant of Mersenne Twister is used.
2. Currently, this library only supports MT19937.

**Comment by fisch123456** [comment]
It's mersenne twister from 2019 developed by matsuo saito and makoto matsumoto and hiroshima university.
